TrainTicketBooking/TrainTicketBooking/Controllers/OrderTicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainTicketBooking.Data;
using TrainTicketBooking.Models;

namespace TrainTicketBooking.Controllers
{
    /// <summary>
    /// Controller for orderering tickets
    /// </summary>
    [Authorize]
    public class OrderTicketController : Controller
    {
        // makes a new database context.
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: OrderTicket
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Creates and places lists into the viewbag
        /// </summary>
        /// <returns>View based on ActionResult</returns>
        public ActionResult OrderTicket()
        {
            ViewBag.TrainId = new SelectList(db.TrainsModels, "Id", "TrainName");
            ViewBag.StationFrom = new SelectList(db.StationModels, "Id", "StationName");
            ViewBag.StationTo = new SelectList(db.StationModels, "Id", "StationName");
            return View();
        }
        /// <summary>
        /// Takes the input from the view the user input and makes a ticket and sends that ticket to the database 
        /// before returning a message if successful and the ticket information to the view.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult OrderTicket(OrderTicketVM model)
        {
            ViewBag.TrainId = new SelectList(db.TrainsModels, "Id", "TrainName");
            ViewBag.StationFrom = new SelectList(db.StationModels, "Id", "StationName");
            ViewBag.StationTo = new SelectList(db.StationModels, "Id", "StationName");

            //check if the values that the user want to input into the database have the same type as the database.
            if (ModelState.IsValid)
            {
                var ticket = new TicketModel { TrainId = model.TrainId, CustomerID = User.Identity.Name, OrderDate = model.OrderDate, StationFrom = model.StationFrom, StationTo = model.StationTo, TravelDate = model.TravelDate };
                db.TicketModels.Add(ticket);
                db.SaveChanges();
                ViewBag.Success = "Your Ticket Successfully Order Thank you...!!!";
                return View();
            }
           
            return View(model);
        }
    }
}

TrainTicketBooking/TrainTicketBooking/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Train Ticket Booking System</title>
    <link href="~/Content/admin/plugins/datepicker/datepicker3.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Train Booking System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item active">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Trains", "Trains", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Schedule", "Schedule", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Announcements", "Announcements", "Home", null, new { @class = "nav-link" })</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">@Html.ActionLink("Admin", "Index", "Dashboard", new { Area = "Admin" }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">@Html.ActionLink("My Account", "UpdateProfile", "Manage", new { id = User.Identity.GetUserId()}, new { @class = "nav-link" })</li>
                        }
                    }
                    <li class="nav-item">@Html.ActionLink("Order Ticket", "OrderTicket", "OrderTicket", null, new { @class = "btn btn-secondary my-2 my-sm-0" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!--DatePicker-->
    <script src="~/Content/admin/plugins/datepicker/bootstrap-datepicker.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>